### PR TITLE
Improved spanish language

### PR DESCRIPTION
**Pull request by ppizarror**
Updated spanish (es) language, translated all entries 💯

### CODE REVIEW

**Comment by uggrock** [comment]
Hey @ppizarror ,
and thanks for updating the spanish translations. For managing the i18n we are actually using the https://www.transifex.com/tagspaces/tagspaces/ platform. So if you don't mind I will close this PR and transfer your changes in this platform, so they can included in the next release.

**Comment by ppizarror** [comment]
I've send you a request to join your transifex group 😄

**Comment by ppizarror** [comment]
I've updated all the string entries of the project, please close this issue if you want
Greetings 😄

**Comment by uggrock** [comment]
Thanks a lot for your contribution!

**Pull request closed without merging**
