### PR TITLE
Added function to generate video thumbnails

### PR DESCRIPTION
**Pull request by IHappyDayI**
This implementation creates thumbnails for video files (mp4, webm, ogv, m4v) by capturing a frame of the video at 1.5 s.

### CODE REVIEW

**Comment by uggrock** [comment]
How to you came up with 1.5 s ?

**Comment by IHappyDayI** [comment]
Well, a bunch of videos start with a short fade in. Take any music video for example. To prevent ending up with mostly black preview images I chose 1.5 seconds. 1 second was slightly too early for a few videos I tested with.

One could actually create a more advanced video preview by capturing a hand full of screenshots at different points in time, combine them with ffmpeg into a short video file and use that as preview instead of a static image. That would be an even nicer preview for videos.

**Comment by uggrock** [comment]
I found it funny because, in the PRO version we use 2 seconds for this parameter, here you can leave 1.5 sec. You were very close ....
Another question, why do you left out the max size boundaries.

**Comment by IHappyDayI** [comment]
K, thanks for pointing this out. The video preview images now use the maxSize.

**Pull request merged**
