### PR TITLE
chore: upgrade to GitHub Actions 2.0

### PR DESCRIPTION
**Pull request by rouzbeh84**
this is a small thing for hacktoberfest. thought i'd help you out but also this is a very cool project!!

### CODE REVIEW

**Comment by rouzbeh84** [comment]
fyi, this will probably always fail if it's trying to run the current action per this announcement [github-actions-hcl-workflows-are-no-longer-being-run](https://github.blog/changelog/2019-10-01-github-actions-hcl-workflows-are-no-longer-being-run/)

**Comment by uggrock** [comment]
Hi and thanks for your PR! 
We are accepting PRs only after signing our CLA, which can be found here: https://www.tagspaces.org/contribute/

**Comment by rouzbeh84** [comment]
done

**Comment by uggrock** [comment]
@rouzbeh84 thank you!

**Pull request merged**
